version: '3'
services:
  backend:
    image: cabreraevil/todo-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    container_name: todo-backend
